<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.4" />
  </ItemGroup>
	
    <ItemGroup>
        <ProjectReference Include="..\..\..\Common\Xurmo.Common.Presentation\Xurmo.Common.Presentation.csproj" />
        <ProjectReference Include="..\Xurmo.Modules.Ordering.Application\Xurmo.Modules.Ordering.Application.csproj" />
    </ItemGroup>
	
    <ItemGroup>
      <PackageReference Update="SonarAnalyzer.CSharp" Version="10.4.0.108396">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>
</Project>
