<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Xurmo.Common.Infrastructure\Xurmo.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\Xurmo.Modules.Ordering.Application\Xurmo.Modules.Ordering.Application.csproj" />
    <ProjectReference Include="..\Xurmo.Modules.Ordering.Presentation\Xurmo.Modules.Ordering.Presentation.csproj" />
  </ItemGroup>

</Project>
