<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Xurmo.Common.Application\Xurmo.Common.Application.csproj" />
    <ProjectReference Include="..\Xurmo.Modules.Catalogs.Domain\Xurmo.Modules.Catalogs.Domain.csproj" />
    <ProjectReference Include="..\Xurmo.Modules.Catalogs.IntegrationEvents\Xurmo.Modules.Catalogs.IntegrationEvents.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="SonarAnalyzer.CSharp" Version="10.4.0.108396">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
